---
title: "tolivar_Tipología"
author: "Mariana Tolivar Baqué"
output:
  html_document:
    toc: true
    toc_depth: 3
  
---

#                     **Práctica 2: Limpieza y análisis de datos**

## 2.Integración y selección de los datos de interés a analizar


  **a)**Selección

```{r}
dataset3 <- read.csv("C:/Users/maria/OneDrive/Escritorio/Dataset3.csv", sep=";")
desarrollados <- subset(dataset3,Level.of.development == "Developed")
datafinal <- subset(desarrollados, European.Union.Membership == "Member")
datafinal
```


## 3.Limpieza de los datos
**3.1. Elementos vacíos**

```{r}
sapply(datafinal, function(x) sum(is.na(x)))
```


**3.2. Valores extremos**
```{r}
women.entre.bp <- boxplot(datafinal$Women.Entrepreneurship.Index, main ="Women.Entrepreneurship.Index")
entrepr.bp <- boxplot(datafinal$Entrepreneurship.Index, main ="Entrepreneurship.Index")
inflation.bp <- boxplot(datafinal$Inflation.rate, main ="Inflation.rate")
female.bp <- boxplot(datafinal$Female.Labor.Force.Participation.Rate, main ="Female.Labor.Force.Participation.Rate")
```


## 4. Análisis de los datos

**4.1. Selección de grupos a analizar**

```{r}
grupo1 <- subset(desarrollados, European.Union.Membership == "Member")
no.desarrollados <- subset(dataset3,Level.of.development == "Developing")
grupo2 <- subset(no.desarrollados, European.Union.Membership == "Not Member")
```




**4.2. Normalidad y homogeneidad de la varianza**
NORMALIDAD

```{r}
shapiro.test(grupo1[,6])
shapiro.test(grupo2[,6])
```

HOMOGENEIDAD DE LA VARIANZA

```{r}
var.test(grupo1$Women.Entrepreneurship.Index, grupo2$Women.Entrepreneurship.Index)
```


**4.3.Análisis estadísticos**

CORRELACIÓN
```{r}

dataset3$Level.of.development <- as.numeric(dataset3$Level.of.development == "Developed")
cor(dataset3$Women.Entrepreneurship.Index,dataset3$Level.of.development)

dataset3$European.Union.Membership <- as.numeric(dataset3$European.Union.Membership == "Member")
cor(dataset3$Women.Entrepreneurship.Index,dataset3$European.Union.Membership)

```




